[package]
name = "server"
version = "0.1.0"
authors = ["Paulo <paulosanz@poli.ufrj.br>"]
edition = "2018"
description = "Internet of Plants - Monitor Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = { version = "0.2", features = ["tls"] }
tokio = { version = "0.2", features = ["macros", "rt-core", "time"] }
http = "0.2"

derive_more = "0.99"
sqlx = { version = "0.3.5", default-features = false, features = [ "runtime-tokio", "macros", "postgres" ] }

pretty_env_logger = "0.4"
log = "0.4"

serde = {version = "1.0", features = ["derive"] }
serde_json = "1"

rand = "0.7"

codegen = { path = "./codegen" }

names = "0.11"

bcrypt = "0.8"
