[package]
name = "server"
version = "0.1.0"
authors = ["Paulo <paulosanz@poli.ufrj.br>"]
edition = "2018"
description = "Internet of Plants - Monitor Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = { version = "0.3", features = ["tls", "multipart"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
bytes = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "fs"] }
hyper = { version = "0.14", features = ["stream", "server", "http1", "tcp", "client"] }
http = "0.2"

md5 = "0.7"

derive_more = "0.99"
sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-native-tls", "macros", "postgres", "chrono"] }

pretty_env_logger = "0.4"
log = "0.4"

serde = {version = "1", features = ["derive"] }
serde_json = "1"

rand = "0.8"

codegen = { path = "./codegen" }

names = "0.11"

bcrypt = "0.8"

chrono = { version = "0.4.19", features = ["serde"] }
