#!/bin/bash

sh dependencies/env
source .config

export DATABASE_URL=postgres://iop:iop@localhost/iop
export LANG=C.UTF-8

if [[ -z "$AUTH_TOKEN" ]]; then
	echo "Please set the authentication token (AUTH_TOKEN env var) used by the CI"
	exit
fi

while true; do
	git checkout deploy
	rm -rf ../last_state;
	mkdir -p ../last_state
	cp ./** ../last_state -r

	git fetch origin deploy
	git reset --hard origin/deploy

	diesel migration run
	if [[ $? -ne 0 ]]; then
		mv ../last_state/** ./ -f
	else
		rm ../last_state -rf
	fi

	cargo build --bin iop --release
	cargo build --bin deploy-watcher --release
	killall iop deploy-watcher
	cargo run --bin iop --release &
	cargo run --bin deploy-watcher --release
done
