#!/bin/bash

export LANG=C.UTF-8

sudo apt-get update -y
sudo apt-get install -y build-essential gcc libsodium-dev postgresql-10 curl libpq-dev make pkg-config
sudo apt-get autoremove -y

if [[ -z "$(which rustup)" ]]; then
	curl https://sh.rustup.rs -sSf | sh -s -- -y
fi

sudo cp dependencies/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
sudo su - postgres -c "psql -c \"CREATE USER iop WITH PASSWORD 'iop';\""
sudo su - postgres -c "psql -c \"ALTER USER iop WITH SUPERUSER;\""

export DATABASE_URL=postgres://iop:iop@localhost/iop
if [[ -z "$(which diesel)" ]]; then
	cargo install diesel_cli --no-default-features --features "postgres"
fi
diesel setup

sudo sh dependencies/networking
